# Generated by Django 5.1.2 on 2024-11-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_offer_availability_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='availability_end',
            field=models.DateTimeField(default='2021-01-01T00:00'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='availability_start',
            field=models.DateTimeField(default='2021-01-01T00:00'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('water', 'Water'), ('clothing', 'Clothing'), ('shelter', 'Shelter'), ('medical', 'Medical Supplies'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(default='No description given'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=11),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(default='No title given', max_length=100),
        ),
    ]
