# Generated by Django 5.1.2 on 2024-11-02 11:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_offer_availability_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='availability_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='offer',
            name='availability_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('water', 'Water'), ('clothing', 'Clothing'), ('shelter', 'Shelter'), ('medical', 'Medical Supplies'), ('other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='Pending', max_length=11),
        ),
    ]
