# Generated by Django 5.1.2 on 2024-11-02 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_offer_availability_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_offers', to=settings.AUTH_USER_MODEL),
        ),
    ]
