# Generated by Django 5.1.2 on 2024-11-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_offer_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='location',
            field=models.CharField(default='No location given', max_length=255),
        ),
    ]
