# Generated by Django 5.1.2 on 2024-11-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_offer_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='location',
            field=models.CharField(default='No was location given', max_length=255),
        ),
    ]
