# Generated by Django 5.1.2 on 2024-11-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0003_request_accepted_by_request_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='location',
            field=models.CharField(default='No location given', max_length=255),
        ),
    ]
