# Generated by Django 5.1.2 on 2024-11-07 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0006_alter_request_accepted_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='accepted_by',
        ),
        migrations.AddField(
            model_name='request',
            name='accepted_by',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='accepted_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
