# Generated by Django 5.1.2 on 2024-11-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default='', max_length=150),
        ),
    ]
